# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &k3s-1 age1exvwh5t9mga7am4ejajq2fggygrryuqs86q82wx2x76escv0l37qq9pka3
  - &k3s-2 age15xg47ssp4s3cr3zmvh3gsvqdkupf3gcmn6t7l3cdluzr7a487crs584f3n
  - &rune-laptop age1fn434n9cah636023wyxc0mhlxlqn4c4kly6lnpy8vrp0sc63xgaqmkkjm8
creation_rules:
  - path_regex: secrets/k3s/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *rune-laptop
          - *k3s-1
          - *k3s-2
