{
  imports = [
    ./csvview.nix
    ./diffview.nix
    ./git-sign.nix
    ./guess-indent.nix
    ./hlchunk.nix
    ./illuminate.nix
    ./lspsaga.nix
    ./lualine.nix
    ./markdown-preview.nix
    ./marks.nix
    ./neoscroll.nix
    ./noice.nix
    ./oil-git-status.nix
    ./rainbow-delimiters.nix
    ./snacks.nix
    ./scheme
    ./trouble.nix
    ./which-key.nix
  ];
}
